### ISSUE TITLE
[Website] Create shareable hyperlinks on pricing page

### ISSUE THREAD

**Issue by manojradhakrishnan** [juspay/hyperswitch-docs#10]
The pricing page has two tabs - open source and cloud hosted. 

It will be great if we can have each of the tab as a unique hyperlink which can be shared. Because some audience look for open source, while others are mostly interested in the cloud version.

**Comment by VedantKhairnar** [comment]
Sharing separate links for the cloud-hosted and the open-source pricing:
[https://hyperswitch.io/pricing?plan=cloud-hosted
](https://hyperswitch.io/pricing?plan=cloud-hosted
)[https://hyperswitch.io/pricing?plan=open-source](https://hyperswitch.io/pricing?plan=open-source)
