### ISSUE TITLE
📚[INFO] Missing estimate on cost of AWS resources for prototyping purpose

### ISSUE THREAD

**Issue by manojradhakrishnan** [juspay/hyperswitch-docs#14]
### Category

Installation Guide

### Summary

Problem:
Developers would want to have an estimate on the AWS resource cost while installing Hyperswitch.

Solution:
- Provide an indicative estimate for running the cloud formation scripts with the mentioned resources
- Earlier Hyperswitch Installation guide had a Free tier deployment option. Shall we republish it ?

### Context

Problem:
Developers would want to have an estimate on the AWS resource cost while installing Hyperswitch.

Solution:
- Provide an indicative estimate for running the cloud formation scripts with the mentioned resources
- Earlier Hyperswitch Installation guide had a Free tier deployment option. Shall we republish it ?

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by shakthi-22** [comment]
https://docs.hyperswitch.io/hyperswitch-open-source/deploy-hyperswitch-on-aws/full-stack-deployment/deploy-on-aws-using-cloudformation#estimated-cost-of-running-the-above-setup
