### ISSUE TITLE
📚[DOCS ISSUES] Add docs for new connectors

### ISSUE THREAD

**Issue by NarsGNA** [juspay/hyperswitch-docs#19]
### Category

- [ ] About Hyperswitch
- [ ] Hyperswitch Open Source
- [ ] Hyperswitch Cloud
- [ ] Features
- [ ] API Reference
- [ ] Installation Guide
- [ ] Troubleshooting
- [X] Missing Connector
- [ ] Other (Specify)

### Summary

Docs to be added for the following recently integrated connectors:

- ProphetPay
- Volt
- Bank of America
- GoCardless
- Square

### Are you willing to submit a PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by VedantKhairnar** [comment]
Thanks Sakil for the contribution. Changes are merged by Nars.
Closing the issue.
