### ISSUE TITLE
[Enhancement] Discoverability of the sample code snippets

### ISSUE THREAD

**Issue by manojradhakrishnan** [juspay/hyperswitch-docs#3]
Solution:
Hyperswitch web integration already supports sample apps for various technologies and it is available here: https://github.com/orgs/juspay/repositories?q=A+simple+integration+App+&type=all&language=&sort=

1. The discoverability of the sample apps on Github could be made easier from the "Web" section
2. Introduce a call to action for developers to request sample code for new technology

**Comment by VedantKhairnar** [comment]
@manojradhakrishnan 
Regarding the _call to action_, should the contributors be welcome to provide sample code for new tech?
Most of the things from hyperswitch perspective are same with minor changes from the language perspective.

**Comment by VedantKhairnar** [comment]
Sample Code apps available in the docs [here](https://docs.hyperswitch.io/hyperswitch-cloud/integration-guide/web/sample-code-apps).
