### ISSUE TITLE
[Website] Text alignment is broken on mobile view

### ISSUE THREAD

**Issue by manojradhakrishnan** [juspay/hyperswitch-docs#9]
The text alignment on pricing page is broken on mobile view. 

![Screenshot_2023-12-15-18-36-12-758_com.android.chrome-edit.jpg](https://github.com/juspay/hyperswitch-docs/assets/34711289/9ecc1961-7a21-42fa-bf00-5c2b47e0e644)

**Comment by AkshayaFoiger** [comment]
Fixed the text alignment issue of pricing page
